### ISSUE TITLE
Brainstorm hosting solutions

### ISSUE THREAD

**Issue by ghost** [Ho-Lab-Colostate/zhunt#1]
ColoState: https://www.acns.colostate.edu/web-hosting/#1471038723919-711f1259-36c0
AWS: [db.t3.small](https://aws.amazon.com/rds/mysql/pricing/) costs about $24/month running full-time (I will probably run not even close to this)
**NOT RECOMMENDED** CSU serves VMs: http://campuscloud.colostate.edu/pricing.aspx

**Comment by ethho** [comment]
Not interested in data mining at the moment, so we don't need to host a DB, just a Linux box where the Flask app can live.
